### ISSUE TITLE
Create Redux -> Rematch migration guide

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#220]
Create a guide for migrating from Redux to Rematch.

Eg:

1. Redux
2. configure redux in rematch init
3. move reducers to models

**Comment by nWidart** [comment]
That would be nice!

**Comment by nWidart** [comment]
Hello,

I'm testing this package out by following the migration guide.

However, I can't seem to reproduce it. This is how I create my store currently with redux:

```js
export const store = createStore(
  rootReducer,
  composeWithDevTools(applyMiddleware(thunk)),
);
```

My `rootReducer` contains all reducers from the app combined with the `combineReducers` function from redux.

```js
const rootReducer = combineReducers({
  ...activationTypesReducerObject,
  ...accountsReducerObject,
  ...authenticationReducerObject,
  ...programRootReducer,
});

export default rootReducer;
```

Following step 1, this is what I have, but doesn't work:

```
export const store = init({
  redux: {
    reducers: {
      rootReducer
    },
    middlewares: [thunk]
  },
});
```

I tried using the reducers directly here instead of going through the `rootReducer`, but then I'm getting the following error:

```
export const store = init({
  redux: {
    reducers: {
      authenticationReducerObject,
    },
    middlewares: [thunk]
  },
});
```

```
Type '{ react_auth__authentication: (state: AuthenticationState, action: any) => AuthenticationState; }' provides no match for the signature '(state: any, payload?: any): any'.
```

I'm also unsure how to setup the `composeWithDevTools()` function.

Thanks!
