### ISSUE TITLE
Is it possible to nest models

### ISSUE THREAD

**Issue by fkrauthan** [rematch/rematch#230]
I was wondering if there is any way to nest models as I can nest redux reducers?

**Comment by ShMcK** [comment]
Interesting. I was unaware you could use multiple `combineReducers` functions.

I suspect you can do the same thing within a reducer by importing `combineReducers`. Worth a try in codesandbox.

```js
import { combineReducers } from 'redux'
import { reducer1, reducer2 } from './reducers'

const count = {
  reducers: {
    allCounts: (state, payload) => ({
        objectWithValues: combineReducers({ reducer1, reducer2 })
    })
  }
}
```

**Comment by ShMcK** [comment]
However, the more I think about it, the more I think it might be an anti-pattern.

I could be wrong, but I believe it would be easier to just have more flattened, normalized data.

**Comment by fkrauthan** [comment]
I have actual two use-cases in mind. One is the demo that demonstrated nested reducers with redux here: https://gist.github.com/sergiodxa/444b6efdbfa4c604df5b1f1017a61cea
Second would be to subdivide data. If you have a really big application you will cause all sorts of trouble with a flat structure which will make it very hard to maintain.

**Comment by ShMcK** [comment]
At work, we have a few applications of considerable size using Rematch. For example, I worked an app today with 25 models. There are always a menu of approaches, but I can only give advice towards what I've done, and whether I felt like it worked well or not.

### Scalable Reducers

Some approaches to scalable Redux applications that maintain a flat structure:

- Avoid putting too much data into Redux. If it is used only once, only load it in the view, and throw it away when the component unmounts
- Avoid using Redux for UI if possible, it only makes things slower
- Keep data normalized, so that you only hold the minimal amount of state. By "normalized", I mean instead of having arrays of objects with ids, have an object keyed on id that can be referenced whenever needed
- Break things into smaller reducers (or models), and name them well. Even consider namespacing them, if your app is large enough
- If you have a data that is deeply nested and changes often, consider using Immutable.js or Seamless Immutable.

### Performance

There are risks when considering how deeply nested data works in terms of performance. For example, in React, if an object changes it will trigger a re-render. Compare the following:

1. a deeply nested object - if it changes anywhere, a re-render will trigger
2. 3 small objects - these will only change individually on changes

I think in most cases, option 2 is preferable.

---

Would love to hear your thoughts.

**Comment by fkrauthan** [comment]
That sounds very good. I just wonder about the `namespacing` approach. How could you namespace things currently in rematch. Or would you use a convention with e.g. `_` as separator for your model names?

**Comment by ShMcK** [comment]
I think any consistent approach is okay.

In my case, I have an alert system at work that is broken into smaller models. Each is prefaced with the word "alert" and camelCased.

[Category Noun] [Specific Noun]

Nothing special there.

**Comment by ShMcK** [comment]
May add this to an FAQ at a later point, but will close for now.

**Comment by Cloudo** [comment]
First of all, thanks for awesome library!
I'm not clear how to create reusable models.
For example in redux I have reusable ducks like this one:

```js
/* @flow */
import { handleActions, createAction } from 'redux-actions'
import { createNamedWrapperReducer } from 'utils/reducers'
import keyMirror from 'utils/keymirror'

const prefix = 'fetch'

export const types = keyMirror(
  {
    FETCH_STARTED: null,
    FETCH_SUCCESS: null,
    FETCH_FAILURE: null,
  },
  prefix
)

export type FetchReducer<Payload> = {
  isFetching: boolean,
  isFetched: boolean,
  payload: Payload,
  errorMessage: ?string,
}

const fetchReducer = handleActions(
  {
    [types.FETCH_STARTED]: state => ({
      ...state,
      isFetching: true,
      isFetched: false,
      errorMessage: null,
    }),
    [types.FETCH_SUCCESS]: (state, { payload }) => ({
      ...state,
      isFetching: false,
      isFetched: true,
      payload,
      errorMessage: null,
    }),
    [types.FETCH_FAILURE]: (state, { payload }) => ({
      ...state,
      isFetching: false,
      isFetched: true,
      errorMessage: payload,
    }),
  },
  {
    isFetching: false,
    isFetched: false,
    payload: null,
    errorMessage: null,
  }
)

const getFetchReducer = (name: string) =>
  createNamedWrapperReducer(fetchReducer, name)
export default getFetchReducer

export type Actions<Payload> = {
  fetchStarted(any): createAction<string, void, Function>,
  fetchSuccess(payload: Payload): createAction<string, Payload, Function>,
  fetchFailure(err: string): createAction<string, string, Function>,
}

export const actions = <Payload>(name: string): Actions<Payload> => ({
  fetchStarted: createAction(types.FETCH_STARTED, undefined, () => ({ name })),
  fetched: createAction(types.FETCH_SUCCESS, undefined, () => ({
    name,
  })),
  fetchFailure: createAction(types.FETCH_FAILURE, undefined, () => ({
    name,
  })),
})
```

and usage:
```js
const appReducer = combineReducers({
  page1: combineReducers({ 
      data: fetchReducer(PAGE1_CONST.FETCH_DATA),
      meta: fetchReducer(PAGE1_CONST.FETCH_META)
  }),
  page2: combineReducers({ 
      data: fetchReducer(PAGE2_CONST.FETCH_DATA),
      meta: fetchReducer(PAGE2_CONST.FETCH_META)
  })
})  
```
I have several pages and each page has to start different set of requests when loaded.
With code above I have quite low amount of boilerplate.

I dont like the idea of namespace, cause in this case it will be very large flat store:
```
{
    page1_data,
    page1_meta,
    ...
    page2_data,
    page2_meta,
    ...
}
```

... and sometimes I have to reset page state to default. It's easy with nested reducers.

Or another example - tables.
They have several reusable actions, reducer and selectors:

```js
export type Actions = {|
  setTotal: number => Action,
  changePage: number => Action,
  changePageSize: number => Action,
  changePageAndFetch: (page: number) => ThunkAction,
  changePageSizeAndFetch: (pageSize: number) => ThunkAction,
  changeSortAndFetch: (sort: Sort) => ThunkAction,
|}

//...

const getQueryParams = getTableState =>
  createSelector(getTableState, ({ page, pageSize, sort }) => ({
    limit: pageSize,
    offset: page * pageSize,
    sort,
  }))

const getPages = getTableState =>
  createSelector(getTableState, ({ total, pageSize }) =>
    Math.ceil(total / pageSize)
  )

```
I think it will be cool to create reusable models and just plug them into store, but I confused with this flat structure.

What do you think?

**Comment by amorphius** [comment]
I'm actually surprised that creators of Rematch didn't think of nested models. I have no idea how to create big complex app with flat structure. This issue actually forces me not to use Rematch in my home project because it seems that it suitable only for micro projects. Redux and combineReducers is the only choice. Too sad.

**Comment by jackwilsdon** [comment]
If there's something you don't like about the library or that you think is missing, why not implement it yourself and open a PR?

**Comment by Cloudo** [comment]
@jackwilsdon what do you think about my post above? is it possible to implement reusable models like that?

**Comment by revskill10** [comment]
Nested models is needed if we want to model state as a state machine, so we need to have nested reducers. We couldn't allow impossible state possible.

So what's the alternatives ?
