### ISSUE TITLE
Arguments Switched for Reducers and Effects

### ISSUE THREAD

**Issue by gpolonus** [rematch/rematch#233]
Hello,

I just started utilizing this library, and I'm finding it much quicker and easier to use than vanilla Redux, so thanks!

I am wondering why arguments for effects and reducers are switched. Working from the React example given:
![image](https://user-images.githubusercontent.com/9874402/36920948-13b0da86-1e28-11e8-9c20-049d7866d576.png)

Not a huge issue, but if they were the same that would be helpful. Thanks!

**Comment by ShMcK** [comment]
Hi @gpolonus, good question.

The idea here is to put params in the order that their most needed. 
This avoid null params like: `addByAsync(null, payload)`

### Reducers
- always need: state (1st)
- sometimes need: payload (2nd)
- rarely need: meta (3rd)

2. Effects
- usually need: payload (1st)
- sometimes need: rootState (2nd) - note, different from reducer state
- rarely need: meta (3rd)

---

Love to hear what you think

**Comment by gpolonus** [comment]
Makes sense to me. Thanks for the quick response!

**Comment by benpolinsky** [comment]
Hi! Thanks for the library! 

You're explanation does make sense, and yet... it just _looks_ wrong to me. I don't have any argument other than consistency. I guess it's interesting API design theory :)

At any rate, I wanted to weigh in because I had the exact same thought before I searched for the 'issue.'
