### ISSUE TITLE
Add support for redux observable or redux saga

### ISSUE THREAD

**Issue by zhDmitry** [rematch/rematch#262]
It would be great to have plugin for redux-observable or redux-saga
```
const module = ({
actions: {
   fetch: action()
},
state: 0, 
  reducers: {
    increment(state, payload) {
      return state + payload
    }
  },
  effects: {
    async incrementAsync(payload, rootState) {
      await new Promise(resolve => setTimeout(resolve, 1000))
      this.increment(payload)
    }
  }, 
epics: {
   randomName(actions$){
          const {fetch} = this.actions;
         actions.ofType(fetch.started).switchMap(el=> //some stuff)
         .takeUntil(fetch.cancel)
  },
// or more hacky way
epics: {
  //take all actions
  fetch(data$){
          data$.mapTo(this.increment).takeUntil(this.actions.fetch.cancel)
  },
  //take only latest
  ['fetch.latest'](data$){
          data$.mapTo(this.increment).takeUntil(this.actions.fetch.cancel)
  },
},
//or
epics: ({ actions })=>({
  [actions.fetch](data$){
          data$.mapTo(actions.increment).takeUntil(actions.fetch.cancel)
  },
  [actions.fetch.latest](data$){
          data$.mapTo(actions.increment).takeUntil(actions.fetch.cancel)
  },
}),
})
```

What do you think about it ? I could try to implement it but i need your advice about design of such feature.

**Comment by ShMcK** [comment]
@zhDmitry interesting idea. 

### Making a Plugin
We have docs for creating plugins: [plugin docs](https://rematch.gitbooks.io/rematch/docs/pluginsApi.html)

Note that in Rematch everything except reducers is a plugin, "effects", "dispatch", etc. There are plenty of examples under [plugins](https://github.com/rematch/rematch/tree/master/plugins) & [src/plugins](https://github.com/rematch/rematch/tree/master/src/plugins).

### Redux Saga
I used to use redux-saga in my code, but no longer find a need for it. As far as I can tell, everything in sagas can be achieved through async/await, or action subscribers.

I made something similar before, that could be used for inspiration: [mirror-saga](https://github.com/ShMcK/mirror-saga).

I quite like your idea of "epic" keys. You might find though, that epics often do not fit easily on a single model.

### Redux Observable
I don't know much about Redux observable to comment.

---

If you have any questions, throw them in this thread. Happy to help.

**Comment by francisrod01** [comment]
But.. There is something that I did know how to do using mirrorx or rematch yet.
https://github.com/ShMcK/mirror-saga/issues/1

**Comment by Utopiad** [comment]
Is there someone working or planning to work on a redux-observable plugin?

**Comment by ShMcK** [comment]
Not to my knowledge.

**Comment by zhDmitry** [comment]
@Utopiad, i was trying to build this plugin but end up with plain redux-observable setup.

**Comment by linonetwo** [comment]
An upside of redux-observable is that it can be dynamically loaded, which is very suitable to build up a plugin architecture.

**Comment by linonetwo** [comment]
http://www.npmtrends.com/redux-loop-vs-redux-promise-vs-redux-saga-vs-redux-thunk-vs-@rematch/core-vs-redux-observable

![redux-loop-vs-redux-promise-vs-redux-saga-vs-redux-thunk-vs-@rematch/core-vs-redux-observable](https://user-images.githubusercontent.com/3746270/43311889-5109e620-91be-11e8-9bb8-6beab80ce5a3.png)
Redux-saga is still very popular.

It can do such thing that rematch can't: loop, for every 3 seconds, save my document to a backend.

**Comment by ShMcK** [comment]
If anyone is interested in setting up a saga plugin, this should help. I wrote something very similar last year (https://github.com/ShMcK/mirror-saga/tree/master/src)

**Comment by alhimik45** [comment]
Just made saga plugin for Rematch https://github.com/alhimik45/rematch-saga
Going to use plugin next month and hope it will be useful not only for me

**Comment by ShMcK** [comment]
Great news :)

Personally, we have a project at work that I wanted to migrate but would involve rewriting a lot of saga code. Love to try it out.

When you're comfortable with the plugin, if you'd like to add a link in the docs - I'd be happy to merge the PR.

**Comment by d3dc** [comment]
From following the issues over in [the repo](https://github.com/alhimik45/rematch-saga/issues/1#issuecomment-441762109)  there's a few outstanding questions needing answers before this would cover most use cases.

I'm closing this for now.

**Comment by KevinGhadyani-minted** [comment]
For integrating with Redux-Observable, a simple method would be exposing `dispatch` in `dependencies`. I actually just wrote a completely unrelated article on doing this last night: https://dev.to/sawtaytoes/the-best-practice-anti-pattern-jj6

I think epics are far more complex and really shouldn't live in an `effects` object on Rematch. Trying to integrate it in there doesn't make much sense since Rematch effects work on action creators.

Epics are independent from action creators and can listen on many different actions at many different points in the pipeline. Technically, the name of an epic doesn't matter since it's never called by anything but Redux-Observable when initializing.

I could help put together some documentation on integrating with Redux-Observable, but a proper implementation would disregard Rematch's `effects` object. If that works for you guys, the next thing is figuring out if having `dispatch` available in the epic is an anti-pattern. That's what my article seeks to argue against; in fact, I'm implying it's actually a best-practice.

If it's not an anti-pattern, I can put a package together that allows better integration between these two libraries with minimal setup effort on the Redux-Observable side of things.

The last quirk are Redux actions in Rematch. There's no way to grab to a Redux action by name, only a way to dispatch them. If the action creator and action name were the same, then it's easy enough to do this: `dispatch.someAction.name`. Rematch's action naming is slightly different though so somehow, those would need to be exposed somewhere.

**Comment by Sawtaytoes** [comment]
For integrating with Redux-Observable, a simple method would be exposing `dispatch` in `dependencies`. I actually just wrote a completely unrelated article on doing this last night: https://dev.to/sawtaytoes/the-best-practice-anti-pattern-jj6

I think epics are far more complex and really shouldn't live in an `effects` object on Rematch. Trying to integrate it in there doesn't make much sense since Rematch effects work on action creators.

Epics are independent from action creators and can listen on many different actions at many different points in the pipeline. Technically, the name of an epic doesn't matter since it's never called by anything but Redux-Observable when initializing.

I could help put together some documentation on integrating with Redux-Observable, but a proper implementation would disregard Rematch's `effects` object. If that works for you guys, the next thing is figuring out if having `dispatch` available in the epic is an anti-pattern. That's what my article seeks to argue against; in fact, I'm implying it's actually a best-practice.

If it's not an anti-pattern, I can put a package together that allows better integration between these two libraries with minimal setup effort on the Redux-Observable side of things.

The last quirk are Redux actions in Rematch. There's no way to grab to a Redux action by name, only a way to dispatch them. If the action creator and action name were the same, then it's easy enough to do this: `dispatch.someActionCreator.name`. Rematch's action naming is slightly different though so somehow, those would need to be exposed somewhere.

**Comment by JiangWeixian** [comment]
https://github.com/JiangWeixian/rematch-observable

welcome use and debugs
