### ISSUE TITLE
loading example not reset on second submit

### ISSUE THREAD

**Issue by Dennis-Smurf** [rematch/rematch#266]
In the example 'react-loading-example' there seems to be a bug:
If you click on 'Submit async' and wait for 2 seconds and click again on this button, than the loading timeout is not reset. The loading disappears after 1 second instead of the expected 3 seconds. In the inspector of the redux devtools:
![afbeelding](https://user-images.githubusercontent.com/4238339/37202825-032c3368-238c-11e8-9157-627942482f9d.png)
The first loading/hide should be dismissed.

**Comment by ShMcK** [comment]
You're right. In order to achieve dismissing of dispatched actions, loading would have to locally store the current dispatches and overwrite them.

There is a current [PR](#245 ) which stores loading as a number (0 or 1). By disallowing a count of 2, this could ensure that loading is not called multiple times.

**Comment by crazy4groovy** [comment]
Ya, this is really the fundamentally broken behaviour I am trying to fix with PR #245. IMO The true/false aspect doesn't work very well, except as a fancy veneer to a counter running behind it.

**Comment by crazy4groovy** [comment]
Should be fixed wit merged PR code, can you verify it @Dennis-Smurf ?

**Comment by Dennis-Smurf** [comment]
It works! Nice solution with the numbering! Gives even more information than true/false. Thanx
