### ISSUE TITLE
Unexpected token ','. Expected a ':' following the property name 'type'.

### ISSUE THREAD

**Issue by kertul** [rematch/rematch#308]
Please help. What's wrong with my code.

My model :
`export default {
    state : 0,
    reducers: {
        setToken : (state, payload) => state + payload
    }
};`

My action : 
`dispatch.auth.setToken(token)`

The result is : "Unexpected token ','. Expected a ':' following the property name 'type'."
But if the code I change to be like this :
`export default {
    state : 0,
    reducers: {}
};`
no error at all.

**Comment by blairbodnar** [comment]
What does your `init` look like?

If you're exporting the model with `default` like in the example above, you're `init` should look something like this:

#### models/auth.js
```js
export default {
  state: 0,
  reducers: {
    setToken: (state, payload) => state + payload
  }
}
```

```js
// index.js
import { init } from '@rematch/core'
import auth from './models/auth'

const store = init({
  models: {
    auth: auth
  }
})

store.getState() // { auth: 0 }
```

**Comment by Reesco** [comment]
Try to turn off "Debug JS Remotely" in emulator.

**Comment by ShMcK** [comment]
@kertul was this an android related issue?
If so, it should be resolved in the latest version.

**Comment by kertul** [comment]
I think this is due to an error during the installation, because when I create a new project and use the same code this problem does not appear.

I remember, this error occurred after I installed axios. Forgive me for being less thorough.

**Comment by jackwilsdon** [comment]
I think this was caused by #299. By defining a reducer, it uses this code;

https://github.com/rematch/rematch/blob/195510662c4de667317873fd7a4abbc4d02bb607/src/utils/getActionCreators.ts#L15-L19

Which is using ES6's enhanced object literals. The issue is that this won't be transpiled by Webpack or any other build tools, as it's inside a string. Ideally the code should have looked like this;

```JavaScript
                const createCreator = new Function('type', `
                    return function(payload) {
                        return { type: type, payload: payload };
                    }
                `);
```

But this has been fixed now in the new version as @ShMcK said.
