### ISSUE TITLE
Experiment with @rematch/core v1

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#332]
Feel free to try out @rematch/core v1.0.0-alpha.0. 

```
npm install @rematch/core@next
npm install @rematch/some-plugin@next
```

We'll try to resolve any issues if they come out.

**Comment by wojciech-bilicki-oke** [comment]
`react-web/node_modules/@rematch/core/typings/rematch/index.d.ts
(50,26): Generic type 'ModelConfig<TState>' requires 1 type argument(s).`

When tried running it with project configured with TS 2.8.1

**Comment by nWidart** [comment]
Are you using redux 4 beta?

**Comment by wojciech-bilicki-oke** [comment]
`3.7.2`

**Comment by ShMcK** [comment]
Added a basic [multistore example](https://github.com/rematch/rematch/tree/master/examples/react/multi-store).

Note: `forceUpdate` is used to avoid having to import `react-redux` in a basic demo.

**Comment by tkivela** [comment]
Tested alpha 1 and it worked well atleast in a small app. I had a problem described in issue #268 with version 0.6 but with this v1 the same worked without any modifications. Good job!

**Comment by kdela** [comment]
Could you please list somewhere versions for each plugins compatible with v1.0?
Latest navigation-plugin is 2.0, latest select-plugin is 1.1.0, and I would love to try this but in the end I don't have too much time for experiments

**Comment by ShMcK** [comment]
@kdela, sorry for the confusion. All v1 plugins are tagged with "next". 

You can install them with `npm install some-plugin@next`

**Comment by tkivela** [comment]
I have a little problem testing effects with 1.0a2, could somebody help? I created issue #350 for it.

**Comment by vadistic** [comment]
Hey, there is tiny issue with typings in `@rematch/select^1.0.0` with `@rematch/core^1.0.0-alpha5`

I've got it by copying your typescript example: `@rematch/select is not a module`, which is kind of weird since it's ts project 😄  

```
// ./node_modules/@rematch/select/dist/index.d.ts

// Invalid
import { Plugin } from '../../../typings/rematch';

// Should be
import { Plugin } from '../../core/typings/rematch';
```

The layout of path in your repository and `@rematch` scope in `node_modules` are different so the imports fail.

Maybe you could consider switching to yarn workspaces/lerna while still in alpha and simply import types from `@rematch/core`?

**Comment by ShMcK** [comment]
@vadistic thanks for figuring out the path issue. 

NPM used to have a very useful `npm link`, which has changed (in my opinion) to be less useful in npm@5.

I'll look into yarn workspaces & lerna.

**Comment by nWidart** [comment]
Yarn has a `link` command too if that helps. I'm using the one from yarn which is working ok.

**Comment by vadistic** [comment]
I was researching this just few days ago and cannot keep myself from praising it a bit, excuse me 😄 

**Yarn workspaces** are more or less automated links that you are talking about.

If you have a `@rematch/core` and more or less ten plugins you would need to prompt `yarn link` in core  and then `yarn link @rematch/core` in each plugin that depend on it. (If your packages would start to depend on each other it would go out of hand really quickly)

Now, when you type `yarn install`  in yarn workspace yarn will look into dependencies and automatically link all required packages.

To set up workspace you simply need to use this
```
{
// needs to be set to private
  "private": true,
  "workspaces": ["directory", "orGlob/**"]
}
```

It got even better few days ago with new yarn 1.7, because it featured *focused workspaces* and you can `yarn (add|install) --focus` to add something quickly for one package during developement without rebuilding whole multirepo.

Lerna generally does all what yarn workspace do (and integrate with it nicely) but also has great tools for i.e versioning and dependency management.

I looked into you `scripts` directory and basically you could get rid of them all, because there are already build in yarn/lerna commands for that.

**Comment by ShMcK** [comment]
I spent some time over the weekend playing around with "yarn workspaces" as well as "lerna". I found they both are well suited for large projects that can be broken down into sub-projects. 

I think `npm link` & `yarn link` both seem to suit the purpose of linking dependencies in the "examples" folder.

There are, however, a few cases where linking dependencies with "peer dependencies" doesn't work. These include the "redux-persist" (React dependency) & "react-navigation" (RN dependency) plugins. 

Thanks everyone for playing around with @rematch/core alpha. I think it's stable enough to move into beta for now.
