### ISSUE TITLE
Step 3 in readme is confusing

### ISSUE THREAD

**Issue by benpolinsky** [rematch/rematch#352]
Or possibly I am confused. Or both.

If you're using React, and react-redux/connect, do you ever have to use `dispatch`?

By stating "dispatch is how we trigger reducers & effects in your models. Dispatch standardizes your actions without the need for writing action types or action creators" and listing this under a 'step' it makes it seem like it's required.

Thanks - really enjoying the library thus far.

**Comment by blairbodnar** [comment]
Hi @benpolinsky ,

True, if you are using React and react-redux, you might only ever interact with dispatch via react-redux's `connect`.

I think in step 3 we're just trying to show that `dispatch` is the same redux `store.dispatch` people are familiar with - and that we enhance it with the `dispatch[model][reducerOrEffect](payload)` shorthand so that you can dispatch either way.

Does that make sense? If not, any suggestions on how we can make it more clear? :)

Thanks!

**Comment by benpolinsky** [comment]
Right, right. Definitely makes sense now.

I do think it could a bit more clear. 
I'll submit a suggestion as a PR if I get a chance today? 
We can see if it's an improvement or not.

Thanks again.

**Comment by blairbodnar** [comment]
Thanks @benpolinsky - yeah sounds great!
