### ISSUE TITLE
'Recipes' for reducers, selectors, etc?

### ISSUE THREAD

**Issue by blairbodnar** [rematch/rematch#44]
@ShMcK @scottclayton 

I'm just brainstorming... Not sure if this is something that we want to rematch to help with or not. But I'm wondering if it would be nice to have some pre-made 'recipes' for common state designs? Not sure if 'recipes' is the right word here... hmm.

@ShMcK We briefly chatted about this the other day. I think I said something along the lines of "I use a lot of similar reducers and selectors, I want to reuse them!". And you said something along the lines of "What if we use object spread?"

So, here's a brain-dump:

I find that as I develop my apps, I tend to come up with a state structure for common things. For example, I end up using the same state structure when dealing with a collection...

Someone:  "Make me a todo-list"
Me: "Ok"
My brain:
#### ./models/todos.js
```js
model({
  name: 'todos',
  // I might have state like this. I kinda like this pattern of `state.id.item`
  state: {
    '2fc9acde': {
      text: 'release rematch to the wild',
      done: false
    },
    'fb6bb0e4': {
      text: 'drink coffee',
      done: true
    }  
  },
  // with reducers like this...
  reducers: {
    addItem: (state, payload) => { ... },
    removeItem: (state, payload) => { ... },
    updateItem: (state, payload) => { ... },
    clearList: (state, payload) => { ... },
    // etc.
  }
  // and selectors like this...
  selectors: {
    getItem: (state, payload) => { ... },
    findById: (state, payload) => { ... },
    getIds: (state) => { ... },
    getItemProperty: (state, payload) => { ... },
    // etc.
  }
})
```
Later on...

Someone: "Make me a shopping cart"
Me: "Ok"
My brain: "Hey, I liked the way I dealt with the collection in my todos model. I think I'll use the same design for this part of my shopping cart..."

So, maybe I move my reducers and selectors somewhere so they can be reused...
#### ./recipes/collection.js
```js
export const reducers = {
  addItem: (state, payload) => { ... },
  removeItem: (state, payload) => { ... },
  updateItem: (state, payload) => { ... },
  clearList: (state, payload) => { ... },
  // etc.
}

export const selectors = {
  getItem: (state, payload) => { ... },
  findById: (state, payload) => { ... },
  getIds: (state) => { ... },
  getItemProperty: (state, payload) => { ... },
  // etc.
}
```
And then use them in models that deal with collections with the same state structure.
#### ./models/todos.js
```js
import { reducers, selectors } from './recipes/collection'
model({
  name: 'todos',
  state: {
    '2fc9acde': {
      text: 'release rematch to the wild',
      done: false
    },
  },
  reducers: { ...reducers },
  selectors: { ...selectors },
})
```
#### ./models/shoppingCart.js
```js
import { reducers, selectors } from './recipes/collection'
model({
  name: 'shoppingCart',
  state: {
    '9bd1e596': {
      item: 'reese peanut butter cups',
      quantity: 99
    },
  },
  reducers: {
    ...reducers,
    anotherReducer:  (state, payload) => { ... },
    // etc.
  },
  selectors: {
    ...selectors,
    anotherSelector:  (state, payload) => { ... },
    // etc.
  },
})
```

**Comment by ShMcK** [comment]
It's true. The idea of a "reducer" can sometime seem redundant when they often do the same thing.

A lot of the power of the recipes above comes from the normalization of the data. Everything is keyed on an id. Unfortunately (or fortunately), redux isn't very prescriptive. Checkout ["redux-normalizr"](https://github.com/paularmstrong/normalizr) for a more standards driven way of structuring your data.

I tend to call my reducers by what they do, rather than their overall model specific purpose. I'm not sure if this is good practice or not. It tends to leave me with few reducers, and more effects.

```js
reducers: {
  set(state, { payload }) {
    return payload
  },
  merge(state, { payload }) {
    return { ...state, ...payload }
  },
}
```

In the end, I think we can recommend some good practices in the docs, but its not essential enough to be core.

**Comment by scottclayton** [comment]
I might be misunderstanding it, but it seems more like a code style or suggestions of best practices that this would address. Is this the intent? I'm not opposed to including them in a README, but it seems like something further down the line, since we'd probably figure them out more as we go.

To be honest I tend to make way too many reducers and don't generalize them much at all, although it could be a good idea. I tend to just name reducers for their specific purposes, with their specific names. There is a set of reducers I made in an app, for example, where I could literally generalize 27 reducers down to 1 and it would be more declarative looking for the dispatch calls!

Actually, this gives me pause…

Let's say I have a dispatch like this:
```js
dispatch.counter.setSelectedBox({ id: 0 })
```

and it triggers a reducer like this:
```js
const setSelectedBox = (state, payload) => ({ ...state, selected: payload.id })
```

it then should update my `state.counter.selected` to `0`.

These set reducers are something I make all the time. I could instead make a generalized `set` reducer that would look like this:

```js
import { cloneObject } from '../../../functions'

const set = (state, payload) => {
  // clones via JSON.parse(JSON.stringify(obj)), but maybe
  // there's probably a better way in lodash or something
  const payloadCopy = cloneObject(payload)

  // since all payloads have a type along for
  // the ride delete the 'type' property
  delete payloadCopy['type']    

  // find all the things we have in our set dispatch
  const payloadCopyKeys = Object.keys(payloadCopy)
  const payloadCopyValues = Object.values(payloadCopy)

  const updated = {}
  payloadCopyKeys.forEach((key, i) => {
    updated[key] = payloadCopyValues[i]
  })

  // return the state with all things from our
  // payload updating their respective state keys
  return ({ ...state, ...updated })
}

export default set

```

then I can call it via something like this:
```js
dispatch.counter.set({ selected: 0 })
```

I could also throw other things in there though too, making it very flexible, e.g.

```js
dispatch.counter.set({ selected: 0, donkey: 'face' })
```

and it would update `state.counter.selected` and `state.counter.donkey` simultaneously.

It could maybe even be generalized further to something like:

```js
dispatch.set({ 'counter/selected': 0, 'user/loggedIn': false })
```
in order to affect multiple models.

Maybe this is off-topic. It could be a bad idea altogether and I might not be thinking it through too.

**Comment by ShMcK** [comment]
I think @scottclayton brings up the underlying decision making.

Is it a better practice to:

### A) next state dictated by dispatch or effect

In this case, reducers are dumb and simple (ie. `set`, `merge`).

Experimental Syntax: `dispatch.set({ 'counter/selected': 0, 'user/loggedIn': false })`

##### Good
Fewer reducers

##### Bad
Calls that can modify state are potentially spread throughout your app

### B) next state dictated by reducer

Reducers are more specific, like "loadItems", "addItem", "removeItem"

##### Good
Everything that modifies state in one place

##### Bad
Reducers may be too specific and boilerplatey

---

I'm actually leaning towards B, even though in practice, I've been doing A.

**Comment by blairbodnar** [comment]
@ShMcK @scottclayton 

Great thoughts and points guys, thanks! 

Yeah, this just started off as a brain dump - not really sure where I was going with it! That being said, I think we all agree that this is more outside the scope of rematch. It's more in the scope of how one designs his or her app. So yeah, I don't think it's really something that should be included with rematch.

It's good to have all our thoughts on this though, because I think from a rematch perspective, we want to make sure that our API plays nice for all developers coming from the 'vanilla' redux world. 

It's great news that so far from our personal experience using the `models` concept introduced by dva, we all tend to agree that reducers work great in a model whether you use the A) or B) approach that @ShMcK mentioned above. 

It's nice that dva, mirror and rematch let A) and B) people live together in peace and harmony 😀😎

**Comment by ShMcK** [comment]
That sounds to me like a closed issue, that we might come back to sometime.
