### ISSUE TITLE
[Question]When will the stable be released?

### ISSUE THREAD

**Issue by DrakeXiang** [rematch/rematch#507]
I noticed there are frequent alpha and beta releases during May and June this year, but suddenly stopped new release for almost two months now, is everything alright?

**Comment by ShMcK** [comment]
In my case, I would say this is largely due to a few factors:
- working on different projects at work where Redux isn't the main form of state management
- a growing interest in using [state charts](https://statecharts.github.io) for state management

I delayed a 1.0.0 release due to:
- TypeScript typings (largely resolved)
- Select Plugin (largely resolved)

**Comment by ShMcK** [comment]
I've put out v1.0.

There remain some issues with plugin related typings, but can be resolved later.
