### ISSUE TITLE
[@rematch/loading] Latest type definitions from yarn with version 1.1.0 does not match source code with latest tag 1.0.0-beta5

### ISSUE THREAD

**Issue by athrunsun** [rematch/rematch#508]
[Latest type definitions from yarn with version 1.1.0](https://cdn.jsdelivr.net/npm/@rematch/loading@1.1.0/index.d.ts)

```typescript
declare const _default: (config?: LoadingConfig) => Plugin<import("../node_modules/@rematch/core/src/typings").Models, Action<any, any>>;
```

This line will cause an TS error:
```
Cannot find module '../node_modules/@rematch/core/src/typings'.
```

---

[Source code with latest tag 1.0.0-beta5](https://github.com/rematch/rematch/blob/1.0.0-beta.5/plugins/loading/index.d.ts)

```typescript
declare const _default: (config?: LoadingConfig) => Plugin<import("../core/src/typings").Models, Action<any, any>>;
```

So this is actually already fixed in tag 1.0.0-beta5, why is it not on yarnpgk.com? Which tag matches version 1.1.0 in yarnpkg.com?

**Comment by jackwilsdon** [comment]
The `1.0.0-beta5` tag you're looking at is actually `@rematch/core` from my understanding - the plugins are versioned separately. Looking at the commit history for `@rematch/loading`, it seems like the problem was fixed in #455, but a new version has not yet been released.

I'm not sure if we need a better way of tagging things, as it does become confusing when the project tags don't line up with plugin versions.

![History for @rematch/loading](https://user-images.githubusercontent.com/1843197/46215509-70537200-c335-11e8-8bbb-c177893c4f79.png)

**Comment by athrunsun** [comment]
@jackwilsdon @ShMcK Is it an option to move plugins into separate repos? Or keeping all plugins in the same repo as `@rematch/core` is intentional from the beginning?

**Comment by jackwilsdon** [comment]
I like the idea of splitting them out into their own repositories, especially seeing as we have control over the @rematch team, but in the end this is up to @ShMcK and @blairbodnar.

**Comment by ShMcK** [comment]
I'm not sure that splitting plugins into their own repos will solve the problem. I would, however, encourage people to fork or develop and release their own plugins. We can link to these plugins in the docs. 

If I've learned anything in open source, its that an "official" solution doesn't necessarily mean it fits your use case or style of programming.

The underlying issue seems to be related to the build package.json pointing to a file path, rather than to a package. This makes local testing more manageable but should be resolved before release. 

I'll look into it now and put out a release.

**Comment by danawoodman** [comment]
This issue also exists for @rematch/immer v1.1.0

https://cl.ly/2dba473fb0d1/Screen%20Shot%202018-11-04%20at%207.37.26%20PM.png

Using @rematch/core v1.0.6

**Comment by danawoodman** [comment]
If I manually change the `index.d.ts` file's import to `import('@rematch/core/src/typing')` my app now compiles. I'm looking for where this invalid import is created but can't find it. @ShMcK could you help me locate this and I'll be happy to submit a PR

**Comment by danawoodman** [comment]
It's strange. Running `npm run build` generates a proper `dist/index.d.ts` file but when you `npm install @rematch/immer` it seems npm changes the path in the `index.d.ts` file to incorrectly point to the wrong path. Any ideas on how this could be fixed @ShMcK?

**Comment by danawoodman** [comment]
I upgraded to `v1.1.0` via `npm i @rematch/immer@next` and the issue goes away!

**Comment by skout90** [comment]
in my case, `v1.1.0` => `v1.0.2`. then the issue goes awa!

````
    "@rematch/core": "1.0.6",
    "@rematch/immer": "1.0.2",
    "@rematch/loading": "1.1.2",
    "@rematch/select": "^2.0.3"
````
