### ISSUE TITLE
[RFC]Let's Document: How to normalize data using Rematch?

### ISSUE THREAD

**Issue by haysclark** [rematch/rematch#533]
I was curious if there is an example of normalizing data with Rematch?

There was a pretty good discussion on this subject in #337; however, I was hoping a more general topic title would get more feedback and ideally examples.  I would love to see a Rematch example similar to the user/articles/comments example in [normalizr's readme](https://github.com/paularmstrong/normalizr).

**Comment by ShMcK** [comment]
The Redux docs provide some best practices: [Normalizing State Shape](https://redux.js.org/recipes/structuringreducers/normalizingstateshape) & [Updating Normalized Data](https://redux.js.org/recipes/structuringreducers/updatingnormalizeddata).

**Comment by d3dc** [comment]
I tote this example around a lot: https://codesandbox.io/s/ql6m574l84

This uses normalizr and reselect (@rematch/select) to closely follow the links @ShMck posted. 

Instead of relying on multiple reducers to store each type of entity, a single reducer handles the abstraction by passing Normalizr schemas. 

This was just a demo of complex selectors; I know delete has several ways it could be handled better. It might be worth it to scale this to the example @haysclark mentioned.

**Comment by d3dc** [comment]
Sticking a pin here, because if there's one guide that needs to exist for Rematch, it's CRUD.

**Comment by d3dc** [comment]
I've worked on an implementation of the [TodoMVC](http://todomvc.com) app [using the toolkit I've been hacking on](https://github.com/d3dc/react-flying-saucer/blob/master/examples/todos)

**Comment by mathieutu** [comment]
@d3dc This issue was automaticaly closed. Could we reopen it? I've exactly the same question.

**Comment by th3d0g** [comment]
Second that.
