### ISSUE TITLE
Typescript example fails to compile

### ISSUE THREAD

**Issue by dcousens** [rematch/rematch#583]
``` js
./rematch/examples/ts/count/src/App.tsx
(14,51): Argument of type '1' is not assignable to parameter of type 'Action<any, any>'.
```

**Comment by dcousens** [comment]
Similar to https://github.com/rematch/rematch/issues/520

**Comment by walkerlin** [comment]
got the same issue using rematch 1.0.6  and typescript 3.2.1

**Comment by raitucarp** [comment]
got the same issue using rematch 1.0.6

**Comment by patsissons** [comment]
I wound up using this to get around the issue (which is essentially that the model shape is not getting inferred from `createModel`.

```tsx
import {createModel, ModelConfig} from '@rematch/core';

export function bindState<S>() {
  return {
    toModel<M extends ModelConfig<S>>(model: M) {
      return createModel<S, M>(model);
    },
  };
}
```

now instead of `createModel<State>({ ... })` you would use `bindState<State>().toModel({ ... })`

**Comment by phmatray** [comment]
I was having the same problem with a CRA2 installation.

During a build, CRA overrides the file tsconfig.json. Assuming that the problem comes from the "react-script" package, it is possible to work around the problem by installing CRA via this link.
https://github.com/Microsoft/TypeScript-React-Starter#typescript-react-starter.

The key was in these lines "react-scripts-ts is a set of adjustments to take the standard create-react-app project pipeline and bring TypeScript into the mix."

No problem encountered with Rematch since then (except a bug with the Immer plugin).

Perhaps we could add a section to the README entitled "How to Start with CRA2 TS?"?

**Comment by danawoodman** [comment]
I've tried @patsissons solution to no effect. Believe I am following the guid exactly. Using a create-react-app application using the new Typescript support and the latest versions of everything:

```js
    "@rematch/core": "1.0.6",
    "@rematch/immer": "1.1.0",
    "@rematch/select": "2.0.3",
    "react": "16.8.1",
    "react-dom": "16.8.1",
    "redux": "4.0.1",
```

**Comment by ShMcK** [comment]
Issue should be resolved in the latest release.
