### ISSUE TITLE
Dispatch with object type not trigger loading/show and loading/hide

### ISSUE THREAD

**Issue by tsl** [rematch/rematch#588]
I found a issue when I using plugins: [loadingPlugin], the action loading/show not trigger, when I dispatch type object like dispatch({ type: 'model/actionName' }), it will trigger when I dispatch.model.actionName.

Case dispatch with object type:

![case-1 1](https://user-images.githubusercontent.com/14858308/49436567-08fde680-f7ec-11e8-80d0-795b6eaa4943.jpg)
![case-1 2](https://user-images.githubusercontent.com/14858308/49436584-10bd8b00-f7ec-11e8-8a72-1f0824581389.jpg)

Case dispatch with mapDispatch:

![case-2 1](https://user-images.githubusercontent.com/14858308/49436618-2337c480-f7ec-11e8-8eb0-8057006c03bb.jpg)
![case-2 2](https://user-images.githubusercontent.com/14858308/49436627-2632b500-f7ec-11e8-8c97-aa1052df9374.jpg)

**Comment by nganhkhoa** [comment]
I think we should fix this, it is more Redux to write `dispatch(ACTION)`. I don't understand why `distach(ACTION)` fails to set loading, because `dispatch.models.effects` is just an alias to `dispatch(ACTION)`.

[createDispatcher](https://github.com/rematch/rematch/blob/ddd44c1e97b56f8843f55e4ea4c4511a6a8358fe/src/plugins/dispatch.ts#L36)

[effects/onModels](https://github.com/rematch/rematch/blob/ddd44c1e97b56f8843f55e4ea4c4511a6a8358fe/src/plugins/effects.ts#L42)

```js
this.dispatch[model.name][effectName] =
	this.createDispatcher.apply(
		this,
		[model.name, effectName]
	)
```
