### ISSUE TITLE
Async initial state

### ISSUE THREAD

**Issue by murtukov** [rematch/rematch#616]
I would like to suggest an idea. I think it would be useful if we had a possibility to set a promise in the initial state.

Suppose we have a registration form with a select dropdown field (cities), which should be filled from remote server. 

Option #1:
```
import { remoteData } from '@rematch/core';

const registration = {
    state: {
        cities: remoteData(getCities, []),
        username: '',
        firstName: '',
        lastName: '',
    },
    reducers: { /*...*/ },
    effects: { /*...*/ }
};
```

In this example we use a special **remoteData** function with 2 arguments:
1 - any callback or a string name of the effect of this model
2 - the default value, while the request is running

When the request is finished the state would be automatically updated.

Option #2:
We could add a new option, e.g. **init**, which holds an array of effect names to automatically call at the start:
```
const registration = {
    init: ['getCities'],
    state: {
        cities: [],
        username: '',
        firstName: '',
        lastName: '',
    },
    reducers: { 
        updateCities: (state, values) => ({
            ...state,
            cities: values
        })
    },
    effects: { 
        async getCities() {
            await axios.post('http://localhos:3000/getDomains')
                .then(response => {
                    this.updateCities(response.data);
                });
        }
    }
};
```

Currently, to make an async request we need to create an effect and pass it via **connect** to the component and call it from "componentDidMount", which is not the nicest way in my opinion, especially if you try to keep your presentational components clean.
I don't know all the logic inside the Rematch plugin, so I just can give you my vision of how would I use this feature.

Thank you.

**Comment by canyavall** [comment]
Correct me if I'm wrong but actually you don't need to connect your component to use an effect. You have to use it in componentdidmount in order to have it in your props when the update component cycle takes place but, if you want to dispatch an effect inside your code, you don't need to connect the state

You have to connect the state whenever you want to re render your component when the global state changes. If you don't need to re render that component or container when the global state changes, then, there's no need to connect that component.

The idea of having the effect call in the constructor would work in your case in order to avoi having to build a React Component class in order to execute componentdidmount and you could do it with a functional component, but, in this case, my recomendation is having a parent container with the fetch in componentdidmount and connected to redux and then prop down the data to a dump child component. THis way, the logic is in the container and the ui is in the child component

**Comment by d3dc** [comment]
IMO, containers are generally an unnecessary abstraction - especially now that react gives us some very nice ways to access context and effects.

My opinion on this is pretty much summed up by a hook I'm working on:
```
function useEffect(mapDispatch, watch = []) {
  const effect = mapDispatch(useDispatch())
  
  useEffect(effect, watch)
}
```

**Comment by semoal** [comment]
D3DC and Miguel answered this pretty clear. I close this.
