### ISSUE TITLE
NPM publish pipeline

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#618]
I've become a bottleneck for Rematch releases. At first, I thought it may be easier to pass the project to someone more involved, but now I wonder if the majority of my role can be automated.

We have great test coverage, which makes me think it may be a good idea to auto-publish releases to NPM.

Following merges into master, Travis could automate the following actions:

1. if code changes are detected in core, automatically deploy to @rematch/core with a tag of dev
2. users can `npm i @rematch/core@dev` to test
3. if there are no issues, I'll manually push a button to upgrade the npm dev version to production

Any thoughts, concerns?

**Comment by blairbodnar** [comment]
Sounds good to me!

**Comment by canyavall** [comment]
First of all, is nice you ask to the community.
In my point of view, is good if you can automate it but, in the other hand, I think would be good if someone than you can push that button too.
Then, another small thing is the maintenance of the issues. Having 33 issues open is not the best way to go for one library.
In my opinion, would be good that someone helps maintaining the library, I think you don't need to traspass it, just keep being the owner/ main maintainer and have some more people to help maintaining it
But that's just IMHO

**Comment by semoal** [comment]
Also sounds good for me, at least, always must be a manual button for publishing the production version

**Comment by olso** [comment]
@ShMcK https://blog.npmjs.org/post/184553141742/easy-automatic-npm-publishes

**Comment by ShMcK** [comment]
I'd like to setup the following GitHub action to test and deploy:
https://github.com/marketplace/actions/automated-releases-for-npm-packages

**Comment by semoal** [comment]
> I'd like to setup the following GitHub action to test and deploy:
> https://github.com/marketplace/actions/automated-releases-for-npm-packages
> 
> Branch "next" can publish to `@rematch/core`@next (for further testing)
> 
> Branch "latest" can publish to `@rematch/core` @latest

I've successfully implemented a github workflow through lerna and conventional commits standard.
You can easily do manual deploys of the next version or master version. 
 
<img width="958" alt="Screenshot 2020-07-29 at 15 15 23" src="https://user-images.githubusercontent.com/22656541/88805720-cd2d4700-d1af-11ea-9777-824e75396701.png">

On push or pull requests automatically runs:
- Install with (cache of node modules) and runs lerna bootstrap.
- Linting
- Testing
- Size testing >5kb

I've integrated husky: 
- Checks that npm run lint passes correctly
- Checks that the commits follows the conventional commits standard.

If we run manually the workflow_dispatch even trigger with:
- next: it will automatically run-> lerna version with x.x.x-next.X version for all the packages, will create the changelog, will tag all the packages and of course create a github release.
- master: it will run the same than next, but using the standard version bumping, 2.0.0 for all packages, and 3.0.0 for @rematch/select, because it's already released the 2.0.0

In this way, we can perfectly merge a bunch of commits to next or master branch and deploy when we want, like 1 version every month, or something like that. 

I'll create right now a next branch and i'll merge our v2 to that branch. We could release the next version when we want since that merge.

**Comment by semoal** [comment]
@ShMcK we must set on the project, the default branch **next** to github listen worfklow_dispatch events, (at least for now, until next and master take the same ci.yml)
