### ISSUE TITLE
Selectors don't receive rootState

### ISSUE THREAD

**Issue by SpadarShut** [rematch/rematch#628]
I'm trying to use selectors, but the functions passed to `createSelector` never receive any arguments. Here's my code (just like in the docs):
```
{
  ...
  selectors: (slice, createSelector) => ({
    location: () => createSelector(
      (rootState, props) => {
		// => both rootState, props are undefined
        return rootState.weather[props.location]
    })
  })
}
```

If the selector gets passed an argument, then the function receives it as first argument, in place of `rootState`.

The selector is called in mapStateToProps as `store.select.weather.today()`.

**Comment by d3dc** [comment]
Hey @SpadarShut 

This behavior is by design. We don't call `getState()` for you. You'll need to pass `state` and `payload` from somewhere (perhaps you already have those values in `mapStateToProps`?)

"Selectors" are an established concept you'll see across libraries outside of rematch. [The docs summarize this here](https://rematch.gitbooks.io/rematch/plugins/select/#basics):

> A "selector" is just a function that uses the current state to derive a value:

> `(state, payload?) => any`

**Comment by d3dc** [comment]
It's worth mentioning you don't need to call `createSelector` if you're not depending on any other selectors. (I thought it was a runtime error from reselect tbh)

**Comment by SpadarShut** [comment]
From the example `const moreThan50 = store.select.cart.expensiveFilter(50.00)` I decided store is passed to selector if called as an object prop. Now I looked further and saw how store is passed also. 
Sorry for troubles and thanks for helping out.
