### ISSUE TITLE
Can 'config' also be a function that accepts 'currentConfig' as a parameter?

### ISSUE THREAD

**Issue by sdujack2012** [rematch/rematch#699]
**Is your feature request related to a problem? Please describe.**
I have been using Rematch for building the data layer of my appliactions. I like that fact that Rematch provides plugin apis that allow for some awesome magic which can't be achieved easily by Redux. But the 'config' in the plugin apis is quite limited and there is no easy way for plugins to communicate on 'config' because 'config' is just an object not a function. As a consequence plugins that modify config may overwrite each other. For example currently Immer and Persist plugin don't work together easily (without hacking, correct me if I am wrong. I just can't make them work together) beacause they both try to provide custom 'combineReducers' in 'config' but whoever comes later wins. 

**Describe the solution you'd like**
I am proposing an improvement for 'config' api. That is, apart from being an object, config can also be a function that accepts paremeter 'currentConfig' which is result from the plugin before the current one. The first plugin will receive a 'currentConfig' that contains models passed from '@rematch/core/init' function just in case some plugin wants to do something for config based on models

**Additional context**
With this addtional feature multiple plugins can easily work together without much change.
For example, for immer and Persist plugin to work together we can rewrite immer for the combineReducer bit into:

![image](https://user-images.githubusercontent.com/7868266/67919414-52b9a180-fbf4-11e9-81a5-dbbe797e59d8.png)

Let me know if this is something you wanted and I don't mind doing a PR for this feature if there is no concern for it

**Comment by pjamrozowicz** [comment]
I stumbled upon the same issue - making plugins work together, specifically Immer and Persist, as well as the lack of ability to create nested persisted reducers. I’m on the mission to make it happen as I really like the idea of rematch ;) but there are some things that need to be done before that - some cleaning up etc. that I’m currently working on, and the time is limited of course so it might take a while.

**Comment by sdujack2012** [comment]
Hi pjamrozowicz,

Thank you for your reply. I also like the idea of Rematch and am keen on I improving it. I would like to contribute to it as well. I have studied the source code for some while now and roughly know how to do it. I understand that we all have our own business to do. But do you mind if I raise a pr for the proposal?

Cheers,
Kai

**Comment by pjamrozowicz** [comment]
I think @ShMcK should answer you, as he is the one in power. Although, I must tell you that I've already offered another solution for this, which is a little bit different than yours and doesn't concern plugins with checking if `combineReducers` is already defined or not.
I would love to implement it right away as it's really not that big, but before we make the code more complicated, it would be nice to first make it much cleaner. That's why I changed the priority a little bit - the lack of this feature still blocks me from using rematch for my current project so you can imagine I'll try to hurry ;)
You could always help with that too if you want!

**Comment by sdujack2012** [comment]
Hi @pjamrozowicz ,

My proposal is not limited to solving just combineReducers and could help solve a range of issues that people have encountered with plugins. But I agree with you that we need to make it cleaner before we implement it.  I'd love to help you with that if you can share with me your solution. I am always happy to help. I have implemented several Rematch plugins for some projects at work and I am keen on contributing to Rematch. 

Cheers,
Kai

**Comment by pjamrozowicz** [comment]
Sure, I'm not saying it's limited to just combineReducers problem - actually it solves many issues so I guess your idea could be implemented too.
It just makes creating plugins a bit more complicated, since you need to understand rematch implementation details and check if combineReducers is already defined etc.

What I had in mind was to also add a couple of additional 'hooks', for example - `onReducer` and `onRootReducer`. A hook would be called when a reducer is created, giving the ability to override or modify it. The result of transpormation by one plugin would be passed to the next one.

Immer plugin can then create a wrapper per reducer, rather than for all reducers at once giving more ability to configure - whitelist/blacklist - what actually uses immer.

The persist plugin would allow using nested persists too, and again - no need to even override the combineReducers, since you can just wrap root reducer using onRootReducer hook. 

I've already implemented it, but like I mentioned, there is too much mess in the code so it needs to be cleaned first.

**Comment by sdujack2012** [comment]
Hi @pjamrozowicz ,

Thank you for your reply. I think our ideas will work well with each other. I really like your idea of onReducer and onRootReducer for providing ability to enhance reducers.

My proposed feature is to provide an option to merge configs provided by mutiple plugins instead of just overriding. Also it is backward compatible. So existing plugins will still work and new plugins can still be implemented the same way.

To use this feature a developer still just needs to understand 'config' plugin apis without knowing the rematch implementation detiails(after all 'combineReducers' is still within the scope of plugin apis). The example I gave was just to show that with the access to 'currentConfig' a plugin will be able to merge configs the way it wants thus it can cater for other plugins that try to 'enhance' the same area. 

More importantly, due to the Rematch implementation, config is currently the only plugin api that allows adding dynamic reducers(correct me if I am wrong). But since config is just an object so it has no access to models. Providing 'currentConfig' that has models in it(which is currently supported by the plugin api) will make plugins that wish to add dynamic reducers based on the models so much easier.

Let me know what yout think about it @ShMcK and @pjamrozowicz . We have three projects starting up with Remacth and I am very keen on contributing to Rematch.

Cheers,
Kai

**Comment by ShMcK** [comment]
> My proposed feature is to provide an option to merge configs provided by multiple plugins instead of just overriding. Also it is backward compatible

I wonder if merging configs might even still be backward compatible for the vast majority of users.

I tend to lean towards a simpler API with fewer options and defaults that fit the majority of use cases. Any breaking changes could be documented in the CHANGELOG.

**Comment by sdujack2012** [comment]
Hi @ShMcK and @pjamrozowicz  ,

Thank you for your reply. To demonstrate what I really want to achieve. I have create a pr in my own forked rematch repo. 
https://github.com/sdujack2012/rematch/pull/1
Please have a look when you have time.

This feature helps create plugins that are smarter and more 'responsible'. With this feature we can have the following benefits:

It is 100% backward compatible. The plugin config can either be a object(existing) or a function(new) so existing plugins will still work and new plugins can be created the same way. The original merge logic is intact. It only changes the way a plugin's config is generated

Plugins that aim to create dynamic reducers or enhance existing reducers can be easily implemented. Config plugin api is the currently the only place where you can add/enhance reducers. With 'models' readily available in 'currentConfig' one can implement something like 'auto reducer' according to the context provided by 'models'

It also helps plugin to deal with conflicts with other plugins on something that is tricky to merge such as combineReducers and createStore. By having the knowledge of the config that is currently applied, a plugin can choose to adapt to it or to throw warnings when it is impossible to be compatible. This prevents plugins override something blindly and cause itself or other plugins to fail silently much like Immer and Persist plugin at the moment.

The PR is WIP. I haven't done the unit tests bit for the new feature let me know if you are fine with then I will continue with the rest of the work.

Cheers,
Kai
