### ISSUE TITLE
Property 'increment' does not exist on type 'never'

### ISSUE THREAD

**Issue by zhangjing28** [rematch/rematch#769]
I got `Property 'increment' does not exist on type 'never'` while running the examples of hooks in ts
**To Reproduce**
just run the https://github.com/rematch/rematch/tree/master/examples/ts/hooks project

Add:
I found the it was because of code [here](https://github.com/rematch/rematch/blob/master/src/typings/index.d.ts#L69) Maybe it can't be `never`.  
And i did some search about [How do I dynamically assign properties to an object in TypeScript?
](https://stackoverflow.com/questions/12710905/how-do-i-dynamically-assign-properties-to-an-object-in-typescript)

**Comment by bdevo1896** [comment]
I have also just run into this problem.  Weird thing is that it was all working fine a week ago and without changing any of my Rematch code or mapped components using the Dispatch, it just all broke with types only. For some reason though, it will still build, run, and execute dispatched reducers, so I'm at a loss for what is happening.

**Comment by bdevo1896** [comment]
So, I did a pretty hacky way of getting the inferred types. The createModel function works pretty well because it gives help in the model and outside for at least the function names and some typing, but the tradeoff of using createModel is that you can't use the dispatch factory. Like so:

`
effects: (dispatch: Dispatch) => ({
//functions go here...
})
`

Now the model looks like this:

`
import { Dispatch, iRootState } from '../index'
import { createModel } from '@rematch/core'
const initialState: string = "test"

export const test = createModel({
  state: initialState,
  reducers: {
      /**
      *Describe your function here
      */
      updateTest (
        state: string,
        payload: {
            newString: string
        },
      ): string {
        let stateCopy: string = state + ""
        
        stateCopy = payload.newString
        return stateCopy
      }
  },
  effects: {
      async updateTestAsync(
          payload: {newString: string, dispatch: Dispatch},
            rootState: iRootState,
        ) {
            const { dispatch } = payload
            console.log(payload)
            dispatch.test.updateTest({newString: payload.newString})
        }
  }
})
`
If you want access to external model dispatch functions, you can pass the dispatch into the payload of the effect. An example mapDispatch will now look like this:

`
//the model being used is called 'test'
const mapDispatch = (dispatch: Dispatch) => ({
  test: () =>
    dispatch.test.updateTestAsync({
      newString: "hey",
      dispatch: dispatch
    })
});
`

What do you guys think of this workaround?

**Comment by zhangjing28** [comment]
@bdevo1896 It works, but when I  try declare the state as an object, I got the property of state does not exist on type 'never'. By the way what's the typescript version on `package.json` in your project

**Comment by bdevo1896** [comment]
> @bdevo1896 It works, but when I try declare the state as an object, I got the property of state does not exist on type 'never'. By the way what's the typescript version on `package.json` in your project

I'm actually stuck on a new problem where RematchDispatch is not typing correctly at import. I'm on typescript version 3.6.5 for testing purposes, but the latest or not, the problem didn't change.

**Comment by naponmeka** [comment]
@zhangjing28 ```Property 'kind' does not exist on type 'never'.``` is related to typescript 3.9 (Intersections Reduced By Discriminant Properties) which is more aggressive. I believe there's some issue within the rematch code base. I'm rolling back to typescript version 3.8.3 for my project. If you are using vscode please make sure the editor is using typescript from the project (open a .ts/.tsx file cmd/ctrl + shift+ p and type ">Select TypeScript Version" and choose your workspace typescript version.

**Comment by zhangjing28** [comment]
@naponmeka Thanks, there is no such error on typescript version 3.8.3.  I agree with you, , So I will keep this open util find issue within the rematch code

**Comment by NoemiRozpara** [comment]
I believe this PR solves this issue https://github.com/rematch/rematch/pull/720 let's keep our fingers crossed for the quick merge 🤞

**Comment by tianzhich** [comment]
I also run into this prob but I did not notice your issue. I also opened one #787 and give some opinions.

And I fixed it in PR #788.

**Comment by semoal** [comment]
Give a try to our next version guys, it's already released. Feel free to submit any issues or something you find interesting.

**Comment by zhangjing28** [comment]
Thanks for you guys, it was recovered on v2.
